# -*- coding: utf-8 -*-
"""Python_Basics_Assignment_2_Adil_Rahman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMmX2VETcUcBq_FNctPNfDAeJABTCKnx

## Question 1: Loop Basics (for loop)

Write a Python program that uses a for loop to print numbers from 1 to 10.
"""

for i in range(1,11):
  print(i)

"""## Question 2: Loop with Condition

Using a for loop, print only the even numbers between 1 and 20.
"""

for i in range(1,21):
  if(i%2==0):
    print(i)

"""## Question 3: String Manipulation

Take a string input from the user and:

1. Print the string in uppercase

2. Print the length of the string

3. Print the string reversed
"""

user_string = input("Enter a string: ")

print("Uppercase:", user_string.upper())
print("Length:", len(user_string))
print("Reversed:", user_string[::-1])

"""## Question 4: String Processing with Loop

Take a string from the user and count how many vowels (a, e, i, o, u) are in the string.
"""

user_input_string = input("Enter a string: ")
vowels = "aeiouAEIOU"
vowel_count = 0

for char in user_input_string:
    if char in vowels:
        vowel_count += 1

print("Number of vowels:", vowel_count)

"""## Question 5: List Comprehension

Given the list:

numbers = [10, 25, 30, 45, 50, 65, 70]
"""

numbers = [10, 25, 30, 45, 50, 65, 70]

filtered_numbers = [num for num in numbers if num > 40]

print("Numbers greater than 40:", filtered_numbers)