# -*- coding: utf-8 -*-
"""Python_Basics_Assignment_Adil_Rahman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18THMyREc53V71tqCPpXT4XRRPZ-g99CP

#Write a Python program that prints the following text exactly:

- Welcome to Python Programming!
- I am learning the basics.
"""

print("Welcome to Python Programming!")
print("I am learning the basics.")

"""#Create two variables:
- name → your name
- age → your age
- Print the output like this:
- My name is Tahmid and I am 25 years old.
"""

name = "Adil Rahman"
age = 24

print(f"My name is {name} and I am {age} years old")

"""#Take user input for:
- Name
- Favorite programming language

- Print a message:
- Hello name, your favorite language is language
"""

print("Enter your name: ")
name = input()

print("Enter your favorite programming language: ")
language = input()

print(f"Hello {name}, your favorite language is {language}")

"""1. Take two numbers from the user using input()
2. Convert them to integers
3. Print their sum

Example output:
The sum is: 30
"""

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

sum = num1 + num2
print(f"The sum is: {sum}")

"""# Take two numbers from the user and:
- Convert them to integers
- Print Addition
- Print Subtraction
- Print Multiplication

Example:
- Addition: 20
- Subtraction: 10
- Multiplication: 75
"""

n1 = int(input("Enter first number: "))
n2 = int(input("Enter second number: "))

# Addition
add = n1 + n2
print(f"Addition: {add}")

# Subtraction
sub = n1 - n2
print(f"Subtraction: {sub}")

# Multiplication
mul = n1 * n2
print(f"Multiplication: {mul}")