# -*- coding: utf-8 -*-
"""Python_Basics_Assignment_3_Adil_Rahman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSXOD_GgN_jrri_ECsUDg67pRJaOw0iP

## Question 1: Enumerate with List
Given the list:

fruits = ["apple", "banana", "cherry", "mango"]

Use enumerate() to print each fruit with its index number.

Output format example:

- 0 apple  

- 1 banana  

- 2 cherry  

- 3 mango
"""

fruits = ["apple", "banana", "cherry", "mango"]

for index, fruit in enumerate(fruits):
    print(index, fruit)

"""## Question 2: Zip with Two Lists
Given two lists:

students = ["Rahim", "Karim", "Ayesha"]

scores = [85, 90, 78]

Use zip() to print each student name along with their score.

Example Output:

- Rahim scored 85  

- Karim scored 90  

- Ayesha scored 78
"""

students = ["Rahim", "Karim", "Ayesha"]
scores = [85, 90, 78]

for student, score in zip(students, scores):
    print(f"{student} scored {score}")

"""## Question 3: Tuple and Loop
Create a tuple of 5 subjects.

Using a for loop, print each subject one by one.
"""

subjects = ("Math", "Physics", "Chemistry", "Biology", "English")

for subject in subjects:
    print(subject)

"""## Question 4: Set Operations
Given the sets:

set1 = {1, 2, 3, 4, 5}

set2 = {4, 5, 6, 7}

Print the common elements using set operation

Print the unique elements of set1
"""

set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7}

print("Common elements:", set1 & set2)

print("Unique elements of set1:", set1 - set2)